# Generated by Django 4.0.6 on 2023-02-19 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_rate_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rate_listing',
        ),
    ]
