# Generated by Django 4.0.6 on 2023-02-01 18:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='listings',
            new_name='Listings1',
        ),
    ]
