# Generated by Django 4.0.6 on 2023-02-02 12:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0002_rename_listings_listings1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Listings1',
            new_name='Listings1s',
        ),
    ]
