# Generated by Django 4.0.6 on 2023-02-02 13:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0003_rename_listings1_listings1s'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Listings1s',
            new_name='listing',
        ),
    ]
